name: Hugo
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49904
title: Hugo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1f2e7'
    - '#c3ce89'
    - '#93995f'
    - '#845a4f'
    - '#368a88'
  brandStrength: 0.6649752811063081
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
