name: Hugo
favicon: null
layout_spectrum: 0.1773466793820262
typography_spectrum: 0.6775366626679897
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6649752811063081
  lightness: 0.053580306470394135
  saturation: 0.135964262066409
  rhythmicContrast: 0.3354735167231411
purpose: []
