name: Hugo
favicon: null
layout_spectrum: 0
typography_spectrum: 0.38966
title: Hugo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3f5e73'
    - '#ffb500'
    - '#78ff05'
    - '#93a4b0'
  brandStrength: 0.6649752811063081
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
